const Route = require('express')
const routRouter = Route()
const authRouter = require('./authRouter')
const categoryRouter = require('./categoryRouter')
const addressTypeRouter = require('./addressTypeRouter')
const addressRouter = require('./addressRouter')
const productRouter = require('./productRouter')
const sizeRouter = require('./sizeRouter')
const contentTypeRouter = require('./contentTypeRouter')
const contentRouter = require('./contentRouter')
const sendEmailRouter = require('./sendEmailRouter')

routRouter.use('/auth', authRouter)
routRouter.use('/categories', categoryRouter)
routRouter.use('/address-types', addressTypeRouter)
routRouter.use('/addresses', addressRouter)
routRouter.use('/products', productRouter)
routRouter.use('/sizes', sizeRouter)
routRouter.use('/content-types', contentTypeRouter)
routRouter.use('/contents',contentRouter)
routRouter.use('/send-email', sendEmailRouter)

module.exports = routRouter